name: Build and Deploy SvelteKit site

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Update if you use a specific pnpm version

      - name: Install dependencies
        run: pnpm install

      - name: Build SvelteKit site
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: datalogger.wazzuracing.vcea.wsu.edu
